spring.application.name=clients-service
# Configuration de la base de donn?es
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=clients_db;encrypt=true;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=SA
spring.datasource.password=Password123

# Configuration JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update

# Affichage des requetes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true